version: '2'

services:
  app:
    image: raivieiraadriano92/node-tools:latest
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    ports:
      - 3000:3000
    tty: true
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7.19
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=snippetfy
